version: '2.4'
services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    network_mode: "host"
    mem_limit: 1G
    volumes:
      - /home/autothon/docker/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock

  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    restart: always
    environment:
      - "TZ=Asia/Kolkata"
      - "JENKINS_SLAVE_AGENT_PORT=50000"
      - "JAVA_OPTS=-Dgroovy.use.classvalue=true -XX:+AlwaysPreTouch -XX:NumberOfGCLogFiles=5 -XX:+UseGCLogFileRotation -XX:GCLogFileSize=20m -Djava.awt.headless=true -server -Xmx2048m -Xms1024m -XX:MaxPermSize=512m -XX:PermSize=256m -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled"
    network_mode: "host"
    mem_limit: 3G
    volumes:
      - /home/autothon/docker/jenkins:/var/jenkins_home
